parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            # 1
            default:
                url: '%env(DATABASE_DEFAULT)%'
                driver: 'pdo_pgsql'
                server_version: '11.0'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_general_ci
    orm:
        default_entity_manager: default
        entity_managers:
            # 1
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App