security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        # Planeswalkers
        ROLE_PLANESWALKERS_USER: [ ROLE_USER ]
        ROLE_PLANESWALKERS_ADMIN: [ ROLE_PLANESWALKERS_USER ]
        # ADMIN
        ROLE_ADMIN: [ ROLE_PLANESWALKERS_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # target: app_any_route # where to redirect after logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/admin, roles: ROLE_ADMIN }
